dist: xenial
language: python
python:
  - "3.7"

install:
  - pip install nbfancy

script:
  - nbfancy render worksheet
  - nbfancy html

deploy:
  provider: pages
  repo: JDBetteridge/samba_induction_python
  target-branch: gh-pages
  local-dir: html
  github_token: $GITHUB_TOKEN
  skip-cleanup: true
  on:
    branch: master
    python: 3.7

