dist: xenial
language: python
python:
  - "3.7"

install:
  - pip install nbfancy
  - pip install -r requirements.txt

script:
  - nbfancy rerun
  - nbfancy rerun worksheet
  - nbfancy render
  - nbfancy render --output_dir=fancyws worksheet
  - nbfancy html
  - nbfancy html --output_dir=html/worksheet fancyws
  - cp html/worksheet/01_python.html html/index.html

deploy:
  provider: pages
  repo: JDBetteridge/samba_induction_python
  target-branch: gh-pages
  local-dir: html
  github_token: $GITHUB_TOKEN
  skip-cleanup: true
  on:
    branch: master
    python: 3.7

